### ISSUE TITLE
Crash for  [PVGTableViewProxy viewModelForIndexPath:]

### ISSUE THREAD

**Issue by alliannas** [plain-vanilla-games/PVGTableViewProxy#26]
Application Specific Information:
**\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'

Last Exception Backtrace:
0   CoreFoundation                       0x00000001858ccf48 **exceptionPreprocess + 124
1   libobjc.A.dylib                      0x000000019a38ff80 objc_exception_throw + 52
2   CoreFoundation                       0x0000000185848ac0 -[__NSArray0 objectAtIndex:] + 108
3   QuizUp                               0x00000001005eae28 -[PVGTableViewProxy viewModelForIndexPath:] + 200
4   QuizUp                               0x00000001005ea730 -[PVGTableViewProxy tableView:didSelectRowAtIndexPath:] + 68
5   UIKit                                0x000000018af9631c -[UITableView _selectRowAtIndexPath:animated:scrollPosition:notifyDelegate:] + 1312
6   UIKit                                0x000000018b053f8c -[UITableView _userSelectRowAtPendingSelectionIndexPath:] + 372
7   UIKit                                0x000000018b11056c _runAfterCACommitDeferredBlocks + 288
8   UIKit                                0x000000018b11d4bc _cleanUpAfterCAFlushAndRunDeferredBlocks + 88
9   UIKit                                0x000000018ae51984 _afterCACommitHandler + 92
10  CoreFoundation                       0x0000000185883bd0 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION** + 28
11  CoreFoundation                       0x0000000185881974 __CFRunLoopDoObservers + 368
12  CoreFoundation                       0x0000000185881da4 __CFRunLoopRun + 924
13  CoreFoundation                       0x00000001857b0ca0 CFRunLoopRunSpecific + 380
14  GraphicsServices                     0x00000001909ec088 GSEventRunModal + 176
15  UIKit                                0x000000018aec8ffc UIApplicationMain + 200
16  QuizUp                               0x0000000100192164 main (main.m:28)
17  libdyld.dylib                        0x000000019abde8b8 start + 0

**Comment by abhisheksagi-glu** [comment]
Fixed
